language: python

os: ubuntu

services:
  - docker

before_install:
  - docker --version
  - cd docker-dev

install:
  - docker build -t underworld .

script:
  - docker run underworld /bin/bash -c "pip3 install pytest; cp -rf /opt/UWGeodynamics /workspace; cd /workspace/UWGeodynamics; python -m pytest -v"
